---
- name: Omarchy system configuration
  hosts: localhost

  roles:
    - role: bloatware_removal
      tags: ['bloatware']

    - role: applications_install
      tags: ['apps']

    - role: hyprland_config
      tags: ['hyprland']

    - role: system_settings
      tags: ['system']

    - role: applications_config
      tags: ['apps-config']

    - role: developer_tools
      tags: ['dev']
